(function extendWindow(defines) {
  function defineROP(k, value){
      Object.defineProperty(window, k, {
          get: function(){ return defines[k] },
          set: function(){ throw new Error('defines.js READ ONLY!!') }
      });
  }
  for(var k in defines){
      defineROP(k, defines[k]);
  }
})({"HOST_INDEX":"www.bdp.cn","HOST_WS":":9990","STATIC_PREFIX":"","FEATURE_ENTERPRISEONLY":false,"FEATURE_PERSONALONLY":false,"GIS_CFG":"{\"USE_CUSTOM_MAP\":true,\"MAP_COORDTYPE\":\"bd09ll\",\"DEFAULT_CENTER\":{\"lng\":117.92395,\"lat\":36.98437},\"DEFAULT_ZOOM\":6,\"CUSTOM_CRS\": \"EPSG4326\",\"DARK_LAYERS\":[{\"url\":\"http://56.3.0.189/tileService/SDMap2000?SERVICE=WMTS&REQUEST=GetTile&version=1.0.0&layer=0&style=default&format=image/png&TileMatrixSet=SDMap2000&TileMatrix={z}&TileRow={y}&TileCol={x}\",\"name\":\"PGIS地图\", \"options\":{\"zoomOffset\":1}}],\"LIGHT_LAYERS\":[{\"url\":\"http://56.3.0.189/tileService/SDMap2000?SERVICE=WMTS&REQUEST=GetTile&version=1.0.0&layer=0&style=default&format=image/png&TileMatrixSet=SDMap2000&TileMatrix={z}&TileRow={y}&TileCol={x}\",\"name\":\"PGIS地图\", \"options\":{\"zoomOffset\":1}}]}","DEBUG":false,"CUSTOM_CONFIG":"{\"SHOW_LOGIN_ANI\":false,\"SHOW_LOGIN_APP\":false,\"HTML_TITLE\":\"\",\"LOGO_PATH\":\"\",\"CHROME_PATH\":\"\",\"SHOW_MACHINE_LEARNING\":false,\"SHOW_DATA_SCREEN\":false,\"SHOW_ADV_DASH\":true,\"USE_CUSTOM_CHART\":true,\"UPLOAD_EXCELMAXSIZE\":100,\"UPLOAD_CSVMAXSIZE\":200,\"PWD_USE_AES\":false,\"HIDE_PASSWORD_WEAK_TIP\":false,\"CREATE_USER_NO_CHECK\":true,\"HIDE_GENERATE_COORDINATE\":false,\"SHOW_DOMAIN\":true,\"DOMAIN\":\"\",\"SHOW_FRIEND_LINK\":false,\"HELP_PATH\":\"\",\"KNOWLEDGE_PATH\":\"\",\"TRAINING_PATH\":\"\",\"USE_MPS_NAV_BG\":false,\"USE_AUTHORIZED\":false,\"PICTURE_LINK\":true,\"NET_EXPORT_WORD\":true,\"SHOW_NET_ON\":true,\"COPYRIGHT_TEXT\":\"\",\"SHOW_BACKHOME\":false,\"WELCOME_TEXT\":\"\",\"LOGO_JUMP\":false,\"HIDE_BROWSER_CHECK\":true,\"SHOW_PRODUCT\":true,\"SHOW_DOWNLOAD\":false,\"TRY_BDP\":\"\",\"SHOW_FORGET_PASSWORD\":false,\"LOGIN_PATH\":\"local-login.html\",\"VIEW_MODEL\":false,\"QUERY_ENGINE\":\"default\",\"BDP_HOME\":\"\",\"GRAFT_OPEN\":false,\"VIEW_DMC\":true,\"CUSTOM_DOMAIN\":\"企业域\",\"LOGO_HREF_PATH\":\"#\",\"ACCOUNT_LOGIN_PATH\":\"http://10.49.10.161/api/ucenter/check/gen_redirect_url?pro_name=bdp&redirect=1&a=1\",\"WATER_MARK\":\"\",\"SHOW_SHARE\":true,\"IS_DMC\":true,\"MARK_PUSH\":false,\"SHOW_ADAPTIVE_FULL_SCREEN\":true}","BUNDLE_MARK":0,"FEATURE_SASSONLY":false,"FEATURE_SAASONLY":false})